### ISSUE TITLE
Hello!I have some error when i compile the source code. asm/barrier.h: No such file or directory

### ISSUE THREAD

**Issue by archichen** [kinglongmee/rapoo-keyboard-driver#8]
OS: Ubuntu 18.04
Kernel: 4.15.0-20-generic

The first, when I make source code, it occurred an exception:
`cc1: error: code model kernel does not support PIC mode`
when I add `KBUILD_CFLAGS := -fno-pic` to Makefile, the problem has been solved.

But occured other exception like `./include/linux/compiler.h:242:10: fatal error: asm/barrier.h: No such file or directory` when I compile again.

So I don't know how to deal this problem, I hope you can help me soon.

Thank you!

**Comment by kinglongmee** [comment]
I am not familiar with ubuntu os.
I code it at centos/fedora os.
Maybe there are some problem on ubuntu os.
Any body know how to compile a kernel module for device on ubuntu?

**Comment by archichen** [comment]
It may be a kernel problem.

Today I have changed my system to ubuntu 16.04, worked fine.

**Comment by kinjes** [comment]
4.13.0-36-generic,work well

**Comment by archichen** [comment]
@kinjes What is your Linux distribution?

**Comment by kinjes** [comment]
@archichen ubuntu 1804.
You could  try  4.15.0-23-generic,it work too.

**Comment by Pioneer-Linzi** [comment]
4.15.0.43-generic has the some problem

**Comment by Pioneer-Linzi** [comment]
> 4.15.0.43-generic has the some problem

I solved this problem when I upgrate my linux kernel to 5.0-generic .

**Comment by laujiting** [comment]
not work on 4.15.0 with the same problem, but works well on kernel 5.3.0
